### ISSUE TITLE
Unable to update the password

### ISSUE THREAD

**Issue by RJK23** [Azure-Samples/ms-identity-dotnetcore-b2c-account-management#12]
Hi Team,
Unable to update password of user after passing oid after passing correct client ID and client secret
![graphapierror](https://user-images.githubusercontent.com/45816994/93076194-9c906680-f6a4-11ea-9d0f-6fa960dfe22f.png)

**Comment by Naakhta** [comment]
@yoelhor @mmacy 

The sample is based on Oauth2 client credential flow and it uses graph client to update the user's password using the passwordProfile attribute of a user.

**Observations**
As per the graph documentation - https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http
A user needs **Directory.AccessAsUser.All** permission to update the **PasswordProfile** property and this permission is not available for **application-context scenario** (client credential flow) hence we are curious to know how exactly the password change will work with this sample.

            var user = new User
            {
                PasswordPolicies = "DisablePasswordExpiration,DisableStrongPassword",
                PasswordProfile = new PasswordProfile
                {
                    ForceChangePasswordNextSignIn = false,
                    Password = password,
                }
            };

            try
            {
                // Update user by object ID
                await graphClient.Users[userId]
                   .Request()
                   .UpdateAsync(user);

                Console.WriteLine($"User with object ID '{userId}' successfully updated.");

**Comment by mmacy** [comment]
@RJK23 @Naakhta Have you added the _User administrator_ role to your application as specified in [Enable user delete and password update](https://docs.microsoft.com/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga#enable-user-delete-and-password-update)?

> ## Enable user delete and password update
> 
> The *Read and write directory data* permission does **NOT** include the ability delete users or update user account passwords.
> 
> If your application or script needs to delete users or update their passwords, assign the *User administrator* role to your application:
> 
> 1. Sign in to the [Azure portal](https://portal.azure.com) and use the **Directory + Subscription** filter to switch to your Azure AD B2C tenant.
> 1. Search for and select **Azure AD B2C**.
> 1. Under **Manage**, select **Roles and administrators**.
> 1. Select the **User administrator** role.
> 1. Select **Add assignments**.
> 1. In the **Select** text box, enter the name of the application you registered earlier, for example, *managementapp1*. Select your application when it appears in the search results.
> 1. Select **Add**. It might take a few minutes to for the permissions to fully propagate.

**Comment by RJK23** [comment]
@mmacy Thanks a lot its working

**Comment by mmacy** [comment]
@RJK23 Excellent! OK to close this issue, then?

**Comment by RJK23** [comment]
Sure @mmacy
