### ISSUE TITLE
Is there an equivalent of this repo for nodejs ?

### ISSUE THREAD

**Issue by abouroubi** [Azure-Samples/ms-identity-dotnetcore-b2c-account-management#15]
Hello,

I'm looking to manage my Azure B2C users from a nodejs API. DO you have some samples on how to do those actions ?

**Comment by derisen** [comment]
@abouroubi you can check out this: [ms-identity-b2c-javascript-nodejs-management](https://github.com/Azure-Samples/ms-identity-b2c-javascript-nodejs-management)

**Comment by abouroubi** [comment]
Exactly what I was looking for.

Thank you.
