### ISSUE TITLE
Extend sample with setting a custom attribute in B2C?

### ISSUE THREAD

**Issue by LockTar** [Azure-Samples/ms-identity-dotnetcore-b2c-account-management#2]
Hi, 

The example is clear but how to create a user with a custom attribute value?

So let's say I have a custom attribute called "GlobalAdmin". 
How can I create a new user with a value for this attribute.
If it is not possible via the graph sdk, how to do this with the new graph?

With the old graph you can do it as described in [my blogpost](https://www.locktar.nl/programming/manage-custom-user-attributes-in-azure-b2c/)

Thanks

**Comment by LockTar** [comment]
OK... found the solution.
Maybe a good idea to add this to the sample project?

```C#
internal class B2cCustomAttributeHelper
{
    internal readonly string _b2cExtensionAppClientId;

    internal B2cCustomAttributeHelper(string b2cExtensionAppClientId)
    {
        _b2cExtensionAppClientId = b2cExtensionAppClientId.Replace("-", "");
    }

    internal string GetCompleteAttributeName(string attributeName)
    {
        if (string.IsNullOrWhiteSpace(attributeName))
        {
            throw new System.ArgumentException("Is mandatory", nameof(attributeName));
        }

        return $"extension_{_b2cExtensionAppClientId}_{attributeName}";
    }
}



internal async Task<string> CreateUser(GraphServiceClient graphClient, CreateUserRequest request)
{
    string b2CInstanceName = "foobar.onmicrosoft.com";
    string b2cExtensionAppClientId = "573c14fb-611f-4ee1-867a-11024853200d";
    string b2cCustomAttributeHelper = new B2cCustomAttributeHelper(b2cExtensionAppClientId);
    string globalAdminCustomAttributeName = b2cCustomAttributeHelper.GetCompleteAttributeName("GlobalAdmin");


    // Fill custom attributes
    IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
    extensionInstance.Add(globalAdminCustomAttributeName, true);
    // Add multiple custom attributes here...

    // Create user
    var result = await graphClient.Users
        .Request()
        .AddAsync(new User
        {
            GivenName = request.FirstName,
            Surname = request.LastName,
            DisplayName = request.FirstName + " " + request.LastName,
            Identities = new List<ObjectIdentity>
            {
                new ObjectIdentity()
                {
                    SignInType = "emailAddress",
                    Issuer = b2CInstanceName,
                    IssuerAssignedId = request.Email.ToLowerInvariant()
                }
            },
            PasswordProfile = new PasswordProfile()
            {
                Password = PasswordHelper.GenerateNewPassword(4, 8, 4)
            },
            PasswordPolicies = "DisablePasswordExpiration",
            AdditionalData = extensionInstance
        });

    return result.Id;
}
```

**Comment by mmacy** [comment]
Excellent, thanks @LockTar! Would you like to submit a PR, by chance?

**Comment by sven5** [comment]
How to query existing custom attributes?
I expected them in AdditionalData but it's not there.
Then I tried to use
`_graphClient.Users.Request().Expand("extensions").GetAsync();`
Still no luck.

**Comment by LockTar** [comment]
> How to query existing custom attributes?
> I expected them in AdditionalData but it's not there.

I'm not sure but I think you need the extensions api for that.

**Comment by LockTar** [comment]
> Excellent, thanks @LockTar! Would you like to submit a PR, by chance?

I think I can find some time for it. Then there must be some remark in the Readme that the new call assumes there is a custom attribute with a specific name.

**Comment by mmacy** [comment]
@LockTar Ideally we'd keep the README pretty lightweight. How about some extended comments in the code, and then a try..catch that handles a missing attribute and mentions on STDOUT the need for an extended attribute named `blah`?

**Comment by LockTar** [comment]
Sample:

![image](https://user-images.githubusercontent.com/1568453/76016799-c579b700-5f1d-11ea-8929-d01b55ef9555.png)

**Comment by mmacy** [comment]
Thanks again for #4, @LockTar! :rocket:
